### ISSUE TITLE
#error pragma intel hd 4600 issue

### ISSUE THREAD

**Issue by vtastek** [zesterer/openmw-shaders#1]
My intel card doesn't like this [line.](https%3A%2F%2Fgithub.com%2Fzesterer%2Fopenmw-shaders%2Fblob%2Facf726cf3865597eb2f4c66983d720f1f693f864%2Fshaders%2Fconfig.glsl%23L87)

`ERROR: 9:90: '' :  illegal character (") (0x22)`

**Comment by zesterer** [comment]
This should be fixed in 8770771. Could you confirm?

**Comment by vtastek** [comment]
No errors.
