### ISSUE TITLE
Editing shaders/config.glsl Has (virtually) no Effect

### ISSUE THREAD

**Issue by Professor-CDawg** [zesterer/openmw-shaders#12]
Hello again!

Once again I want to say that I find your work here amazing. The increase in visual appeal just from installing this mod was immediately noticeable!

I noticed the shadows seemed to be quite dark by default, however, so I opened shaders/config.glsl in Notepad and tried tweaking some settings. 
However, when I got back into the game I saw no difference at all. Just to confirm, I tried setting some values very high so it would be apparent whether there was any effect ingame (e.g. #define SATURATION_FACTOR 3.5). Again, no difference.

The only setting I could seem to get to do anything was WIND_AMPLITUDE . Setting it to a very high value had an obvious (and somewhat amusing) effect. However, the strangeness continued when I tried to disable the wind (#define WIND_AMPLITUDE 0.0). At 0.0, the foliage continued to sway at a fairly noticeable amplitude.

Again I could certainly be doing something wrong.

This is on the latest development build of OpenMW (downloaded this morning).

**Comment by zesterer** [comment]
Have you tried switching between the presets? The vanilla preset should have less harsh contrast between light and shadow. The variable you changed, `SATURATION_FACTOR`, changes the intensity of colour in the scene. You should also check your game logs for errors. It might be that the shaders aren't quite compatible with the latest build (there have been some changes IIRC).

**Comment by Professor-CDawg** [comment]
I just checked the log and I didn't find any errors of any kind 🤔 

I also didn't find any mention of the config.glsl file.

**Comment by Professor-CDawg** [comment]
Not sure if it's relevant to the issue but I also noticed that toggling post processing on and off in the ingame settings has no visible effect (the shaders seem to still be active even when post processing is set to "off")

**Comment by Professor-CDawg** [comment]
> Are you sure you're editing the right file?
I'm editing resources/shaders/config.glsl . Also, changing the WIND_AMPLITUDE value clearly has an effect.

If you mean the log file I checked, that was Documents/My Games/OpenMW/openmw.log .

Let me know if you see anything wrong here :)

**Comment by zesterer** [comment]
What other values are you changing and what effect do you expect them to have? I'm still not sure what it is that is/isn't working.

**Comment by Professor-CDawg** [comment]
I've tried changing SATURATION_FACTOR, SUNLIGHT_STRENGTH, and AMBIANCE_STRENGTH. I tried very high values and very low values for each and I couldn't tell a difference ingame at all for any of them.

I didn't mess with the other values much because they're harder for me to immediately see ingame.

**Comment by Professor-CDawg** [comment]
![screenshot003](https://user-images.githubusercontent.com/68561018/176449428-27da96c9-8f1d-4db3-8c49-667497138b76.png)
![screenshot002](https://user-images.githubusercontent.com/68561018/176449432-e752b18f-0128-4cf7-8dcb-9ee084597a40.png)

[config.glsl.txt](https://github.com/zesterer/openmw-shaders/files/9011013/config.glsl.txt)


Here are some screenshots (after setting SUNLIGHT_STRENGTH to 0.0), and my config.glsl from when they were taken (had to add the .txt extension for github uploading). I still had SATURATION_FACTOR and AMBIANCE_STRENGTH at fairly extreme values as well (from my prior testing).

**Comment by ElectricVersion** [comment]
Am having the same issue; even things that should be fairly easy to discern, like setting saturation to 0.0 seem to do nothing.

**Comment by ElectricVersion** [comment]
Update - enabling "force per pixel lighting" in the settings.cfg file fixed it for me.
