### ISSUE TITLE
Cannot get it to work

### ISSUE THREAD

**Issue by BASEDNWAH** [zesterer/openmw-shaders#15]
I unzipped the file in to my resources folder and launched the game. This is using the 0.48 dev build. I see no difference at all. I then go in the config file and replace the "#define PRESET ZESTERER " with "#define PRESET ZESTERER 2" to try to get the "Colorful and intense fantasy lighting" and it relaunch the game and it looks the exact same still. I am not sure what I'm doing wrong?

Thanks!

**Comment by zesterer** [comment]
Have you followed the instructions [here](https://modding-openmw.com/tips/custom-shaders/#installing) when it comes to installing shader packs?

**Comment by BASEDNWAH** [comment]
> 

This worked! I was just dumping it in resources instead of resouces>shaders. Ty!

**Comment by BASEDNWAH** [comment]
Do you know what settings you use here? 
https://www.youtube.com/watch?v=1KHIZ1DyBS4

This is my screenshot of the game running with 
"#define ZESTERER 2" and it looks pretty washed out. Per pixel lighting is on and light clamping disabled.
![screenshot007](https://user-images.githubusercontent.com/109309480/181918872-8c1b8567-080a-4fe1-9b36-d2fac1c565c7.png)

**Comment by zesterer** [comment]
You shouldn't need to change `#define ZESTERER`, only the `#define PRESET` line, as mentioned in the documentation within the file.

**Comment by BASEDNWAH** [comment]
<img width="589" alt="zesterer shader" src="https://user-images.githubusercontent.com/109309480/182457713-eace5208-50f0-4f83-a08b-a108496c9971.PNG">
This line I have highlighted here right?

**Comment by zesterer** [comment]
Yes, this is wrong. You should change the line to one of the presets, i.e:

`#define PRESET ZESTERER`

or

`#define PRESET CUSTOM`

or

`#define PRESET VANILLA`

etc.

**Comment by BASEDNWAH** [comment]
> 
This worked ty! Looks much more bright now! Still some kind of darkness over it though but I made edits to my settings.cfg for lights and darkness mod that I think are impacting. I will test with default settings.

I never realised that PRESET  had to be kept in and the numbers were not part of the preset names. My bad!

**Comment by BASEDNWAH** [comment]
BOOTS OF BLINDING SPEED WERE MAKING MY GAME LOOK DARKER!!! ... IT FIXED ITSELF IMMEDIATELY WHEN I SWITCHED ON GOD MODE!! VERY SORRY FOR BEING A S'WIT!!

![image](https://user-images.githubusercontent.com/109309480/182714022-7a143ae4-f408-41b9-8b1a-b74a76c2c5ae.png)

**Comment by zesterer** [comment]
> I never realised that PRESET had to be kept in and the numbers were not part of the preset names. My bad!

It's an unfortunate byproduct of the fact that `config.glsl` is actually just regular shader code and not a real 'config file' in the traditional sense of the word.

Happy to hear that it's working well for you now!
