### ISSUE TITLE
Add post processing normals shader changes

### ISSUE THREAD

**Issue by AbduSharif** [zesterer/openmw-shaders#17]
Post Processing MR added shader changes to the core shaders for normals support, this is probably important to have for this shader pack too.

**Comment by zesterer** [comment]
Do you know what changes were made? If there's a diff available, that would be really useful.

**Comment by AbduSharif** [comment]
It's in the post processing merge request in the OpenMW gitlab repo:
https://gitlab.com/OpenMW/openmw/-/commit/04843fed6d5fd7f784912480536b44f6d3c40cec

**Comment by AbduSharif** [comment]
It's in the post processing merge request in the OpenMW gitlab repo:
https://gitlab.com/OpenMW/openmw/-/commit/04843fed6d5fd7f784912480536b44f6d3c40cec

**Comment by zesterer** [comment]
This should be addressed now.
