### ISSUE TITLE
Sun white flashing circle

### ISSUE THREAD

**Issue by zaphida** [zesterer/openmw-shaders#21]
Unfortunately I am experiencing an issue where the sun presents as a white flashing circle. 
Please see this video where I try different view points with the sun behind/not behind buildings and different Volumetric Cloud & Mist Mod settings.
https://www.youtube.com/watch?v=vT57I3ua110
I confirmed it's not the Volumetric Cloud & Mist Mod settings by disabling it in the Postprocess HUD.
[2022-08-25 19-11-15.webm](https://user-images.githubusercontent.com/12946330/186631333-ae89da02-80ea-4f94-8b47-cde9acc04f8a.webm)
Double confirmed by uninstalling the mod by removing the data = line in openmw.cfg
https://www.youtube.com/watch?v=sAC3VfFcSa0

OpenMW 0.48.0 0a16d54865
[openmw.log](https://github.com/zesterer/openmw-shaders/files/9423492/openmw.log) (corresponds to video "Double confirmed") 
openmw.cfg: https://pastebin.com/EKzHZEd5
settings.cfg: https://pastebin.com/S6hthaws

GTX 1650 Max-Q with studio driver 516.94
16GB RAM
i7-10750H
Windows 10 Home 21H2

**Comment by zesterer** [comment]
This bug was present in an older version (see #18 ). Are you using both the latest version of this mod and the latest nightly build of OpenMW?

**Comment by zaphida** [comment]
Apologies for the duplicate bug, I didn't check. Latest nightly build of OpenMW, yes. Just installed latest version of the mod and it's now fixed.

**Comment by zesterer** [comment]
Brilliant, good to hear
