### ISSUE TITLE
Link to OpenMW 0.48 RCs to avoid user issues or possible future conflicts

### ISSUE THREAD

**Issue by AbduSharif** [zesterer/openmw-shaders#27]
Since OpenMW 0.48 testing period has kicked off for a long while now, the development branch has been building up in terms of bug fixes and features and may sooner or later make saves on development builds not backwards-compatible so a user may get locked on them when the shaderpack may only work on 0.48, if you plan on supporting only development builds then please ignore this.

0.48 has been tested alot and it has been rather stable, here's a forum page which has RC builds links:
https://forum.openmw.org/viewtopic.php?t=7486&start=120

**Comment by zesterer** [comment]
Out of interest, do you know when 0.48 is due for release?

**Comment by AbduSharif** [comment]
No one knows so far.

**Comment by AbduSharif** [comment]
Closing as 0.48 has its own branch in this repo...etc.
