### ISSUE TITLE
Conflict- Frame Rate Drain with Remiros' ground Cover mod. 

### ISSUE THREAD

**Issue by nitroinferno** [zesterer/openmw-shaders#30]
Appears that Remiros' Ground Cover mod conflicts with the shaders within this mod. The groundcover gets an extremely darkened appearance and tanks framerate in nearby area. I tried all the shaders pre-config options except for Custom. 
![screenshot016](https://user-images.githubusercontent.com/67395045/210158823-e765b912-18b3-426a-858c-f37857f6dba6.jpg)

Using latest Developmental OpenMW build - 3f6b33820a. Windows version. 

Adding additional detail: This is not due to groundcover plug-ins activated. They are not activated. Just enabled in the config file.

Was also running Glassman's omwfx-shaders, and openmw-volumetric-clouds.
System Specs:
AMD Ryzen 7 5700G with Radeon Graphic 3.80 GHz, 16GB ram, GeForce 3060 Ti

**Comment by zesterer** [comment]
The darkened grass is a known asset issue that I've yet to look into further, but shall do.

Regarding the framerate 'tanking': how did you determine that the problem is this in particular? My shaders add various effects that would have an effect on the framerate independently of groundcover, so I don't see how you might have isolated the groundcover as the specific cause of this.

**Comment by nitroinferno** [comment]
Discovered it while walking around in areas of dense ground cover. For example the eggmine south of Balmora fps drops to single digits. Then I took my character flying upwards until ground cover rendering disappeared with ground still visible, framerate shot back to normal.

Saved a temp save file in area. Loaded back in without shaders -> framerate went back to roughly ~60fps. 

Seems cities also put a big strain on framerate, such as balmora, but not as significant as the ground cover.

**Comment by zesterer** [comment]
I don't think this is necessarily indicative of anything other than that groundcover is inherently expensive, but I can look into it.

**Comment by nitroinferno** [comment]
Sounds likely. Do shaders give the leeway to disable application to certain assets, like ground cover? Could be a neat performance togglable option

**Comment by Puppies-On-Acid** [comment]
The dark grass can be mostly fixed by changing line 119 in groundcover_fragment.glsl from MAT_LEAF to MAT_DEFAULT

**Comment by AbduSharif** [comment]
Groundcover isn't expensive, unless you're loading it the wrong way, or your hardware doesn't handle high densities.

**Comment by nitroinferno** [comment]
Appears the framerate hit was combination of https://www.nexusmods.com/morrowind/mods/49771 compounded by framerate hit from this shader pack as discussed on front page and dense ground cover areas nearby. 


Could not figure out how to fix dark grass. Solution from puppies-on-acid did not work,  line 119 already had MAT_DEFAULT.


..Changing line 119 in groundcover_fragment.glsl from MAT_LEAF to MAT_DEFAULT..

**Comment by AbduSharif** [comment]
They said to change MAT_DEFAULT to MAT_LEAF

**Comment by nitroinferno** [comment]
> They said to change MAT_DEFAULT to MAT_LEAF, (MAT_DEFAULT is already there).

Thanks! Worked great.
