### ISSUE TITLE
Shaders dont work like intended

### ISSUE THREAD

**Issue by franzmondlichtmann** [zesterer/openmw-shaders#4]
Water does look weird. Other Shaders besides shadows do not seem to work.

I use OpenMW 0.47.0 with Steam Version of Morrowind.

I use a Laptop with Nvidia Prime (Geforce 3050 rtx Laptop AND build in CPU Graphics)
Arch Linux, newest Kernel.

I had to create a shaders folder in the existing resources folder (I did not replace any shaders in the process)
/usr/share/games/openmw/resources/shaders/

Example screenshot of permissions attached. All files in shaders/ have the same permissions.

![Screenshot_20220527_085357](https://user-images.githubusercontent.com/105480088/170648244-d9598253-b8d8-46b2-8249-cf4a0fd17828.png)
![Screenshot_20220527_085431](https://user-images.githubusercontent.com/105480088/170648250-2e7b6c19-f783-4232-abb1-b70209aa20ed.png)
![Screenshot_20220527_085603](https://user-images.githubusercontent.com/105480088/170648266-c0ee1648-6315-499e-97cd-32cd5204ce14.png)

Lesen = Reading
Schreiben = Writing
Benutzer = User
Gruppe = Group

If needed, I will provide more Screenshots later!

**Comment by franzmondlichtmann** [comment]
Probably my fault, since I did not use the latest development release of OpenMW.

**Comment by zesterer** [comment]
All working now hopefully?
